/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * freee人事労務 API
 * 
<p>freee人事労務のAPI仕様です。</p>

<hr />

<h2 id="start_guide">スタートガイド</h2>

<p>freee API開発がはじめての方は<a href="https://developer.freee.co.jp/getting-started">freee API スタートガイド</a>を参照してください。</p>

<hr />
<h2 id="specification">仕様</h2>

<h3 id="api_endpoint">APIエンドポイント</h3>

<p>https://api.freee.co.jp/hr</p>

<h3 id="about_authorize">認証について</h3>

<p>OAuth2.0を利用します。<a href="https://developer.freee.co.jp/reference/#%e8%aa%8d%e8%a8%bc" target="_blank">詳細はリファレンスの認証に関する記載を参照してください。</a></p>

<h3 id="data_format">データフォーマット</h3>

<p>リクエスト、レスポンスともにJSON形式をサポートしていますが、詳細は、API毎の説明欄（application/jsonなど）を確認してください。</p>

<h3 id="compatibility">後方互換性ありの変更</h3>

<p>freeeでは、APIを改善していくために以下のような変更は後方互換性ありとして通知なく変更を入れることがあります。アプリケーション実装者は以下を踏まえて開発を行ってください。</p>

<ul>
<li>新しいAPIリソース・エンドポイントの追加</li>
<li>既存のAPIに対して必須ではない新しいリクエストパラメータの追加</li>
<li>既存のAPIレスポンスに対する新しいプロパティの追加</li>
<li>既存のAPIレスポンスに対するプロパティの順番の入れ変え</li>
<li>keyとなっているidやcodeの長さの変更（長くする）</li>
<li>エラーメッセージの変更</li>
</ul>

<h3 id="common_response_header">共通レスポンスヘッダー</h3>

<p>すべてのAPIのレスポンスには以下のHTTPヘッダーが含まれます。</p>

<ul>
<li>
<p>X-Request-Id</p>
<ul>
<li>各リクエスト毎に発行されるID</li>
</ul>
</li>
</ul>

<h3 id="error_response">共通エラーレスポンス</h3>

<p>APIリクエストでエラーが発生した場合は、エラー原因に応じたステータスコードおよびメッセージを返します。</p>

  <table border="1">
  <tbody>
    <tr>
      <th style="padding: 10px"><strong>ステータスコード</strong></th>
      <th style="padding: 10px"><strong>原因</strong></th>
    </tr>
    <tr><td style="padding: 10px">400</td><td style="padding: 10px">リクエストパラメータが不正</td></tr>
    <tr><td style="padding: 10px">401</td><td style="padding: 10px">アクセストークンが無効</td></tr>
    <tr><td style="padding: 10px">403</td><td style="padding: 10px">アクセス権限がない</td></tr>
    <tr><td style="padding: 10px">404</td><td style="padding: 10px">リソースが存在しない</td></tr>
    <tr><td style="padding: 10px">429</td><td style="padding: 10px">リクエスト回数制限を超えた</td></tr>
    <tr><td style="padding: 10px">503</td><td style="padding: 10px">システム内で予期しないエラーが発生</td></tr>
  </tbody>
</table>

<p>メッセージボディ内の <code>messages</code> にはエラー内容を説明する文字列が入ります。</p>
<pre><code>  {
    &quot;status_code&quot; : 400,
    &quot;errors&quot; : [
      {
        &quot;type&quot; : &quot;bad_request&quot;,
        &quot;messages&quot; : [
          &quot;リクエストの形式が不正です。&quot;
        ]
      }
    ]
  }  </code></pre>

</br>

<h3 id="api_rate_limit">API使用制限</h3> 
<p>APIリクエストは1時間で10000回を上限としています。API使用ステータスはレスポンスヘッダに付与されます。</p>
<pre><code>X-Ratelimit-Limit:10000
X-Ratelimit-Remaining:9998
X-Ratelimit-Reset:2018-01-01T12:00:00.000000Z
</code></pre>

<br> 各ヘッダの意味は次のとおりです。</p>

 <table border="1">
  <tbody>
    <tr>
      <th style="padding: 10px"><strong>ヘッダ名</strong></th>
      <th style="padding: 10px"><strong>説明</strong></th>
    </tr>
    <tr><td style="padding: 10px">X-RateLimit-Limit</td><td style="padding: 10px">使用回数の上限</td></tr>
    <tr><td style="padding: 10px">X-RateLimit-Remaining</td><td style="padding: 10px">残り使用回数</td></tr>
    <tr><td style="padding: 10px">X-RateLimit-Reset</td><td style="padding: 10px">使用回数がリセットされる時刻</td></tr>
  </tbody>
</table>

<p>上記に加え、freeeは一定期間に過度のアクセスを検知した場合、APIアクセスをコントロールする場合があります。<br> その際のhttp status codeは403となります。制限がかかってから10分程度が過ぎると再度使用することができるようになります。</p>

</br>

<h3 id="api_rate_limit">プランごとの利用可能API</h3> 

<p>契約プランごとに利用可能なfreee人事労務APIはfreee人事労務のWeb版でご利用できる機能と同様です。例えば、スタンダードプラン（または旧ベーシックプラン）を契約している場合、Web版では打刻機能をご利用いただけますので、APIでもタイムレコーダー(打刻)APIが利用可能です。<a href="https://support.freee.co.jp/hc/ja/articles/203309710" target="_blank">freee人事労務のWeb版のプラン別機能比較はfreee人事労務のプラン・料金についてのヘルプを参照してください。</a></p>

</br>

<hr />
 * OpenAPI spec version: 2022-02-01
 */
import type { ApiV1EmployeeYearendAdjustmentInsuranceSerializerType } from './apiV1EmployeeYearendAdjustmentInsuranceSerializerType';
import type { ApiV1EmployeeYearendAdjustmentInsuranceSerializerCategory } from './apiV1EmployeeYearendAdjustmentInsuranceSerializerCategory';
import type { ApiV1EmployeeYearendAdjustmentInsuranceSerializerNewOrOld } from './apiV1EmployeeYearendAdjustmentInsuranceSerializerNewOrOld';
import type { ApiV1EmployeeYearendAdjustmentInsuranceSerializerPeriod } from './apiV1EmployeeYearendAdjustmentInsuranceSerializerPeriod';
import type { ApiV1EmployeeYearendAdjustmentInsuranceSerializerRecipientRelationship } from './apiV1EmployeeYearendAdjustmentInsuranceSerializerRecipientRelationship';
import type { ApiV1EmployeeYearendAdjustmentInsuranceSerializerCertificationType } from './apiV1EmployeeYearendAdjustmentInsuranceSerializerCertificationType';

export interface ApiV1EmployeeYearendAdjustmentInsuranceSerializer {
  /**
   * 保険料id
   * @minimum 1
   * @maximum 2147483647
   */
  id?: number;
  /** 保険の種類 life_care_pension_insurance: 生命保険・介護医療保険・個人年金保険, earthquake_non_life_insurance: 地震保険・旧長期損害保険, social_insurance: 社会保険, other_insurance: その他の保険（小規模企業共済等） */
  type?: ApiV1EmployeeYearendAdjustmentInsuranceSerializerType;
  /** 区分<br>
保険会社等が発行する証明書類に基づいて区分を設定してください。<br>
保険の種類によって設定可能な値が変わります。<br>
・life_care_pension_insurance<br>
　life: 生命保険<br>
　care: 介護保険<br>
　pension: 個人年金保険<br>
・earthquake_non_life_insurance<br>
　earthquake: 地震保険<br>
　old_long_term_non_life: 旧長期損害保険<br>
・social_insurance<br>
　national_pension: 国民年金<br>
　national_pension_fund_premium: 国民年金基金<br>
　national_health: 国民健康保険<br>
　health: 健康保険<br>
　care_insurance_deduction_of_pension: 介護保険<br>
　employee_pension: 厚生年金<br>
　advanced_elderly_medical: 後期高齢者医療保険<br>
　none: その他（印刷後に手書き）<br>
・other_insurance<br>
　sema: 独立行政法人中小企業基盤整備機構の共済契約の掛金<br>
　idc: 個人型確定拠出年金（iDeCo）<br>
　cdc: 企業型確定拠出年金<br>
　dsma: 心身障害者扶養共済制度に関する契約の掛金<br> */
  category?: ApiV1EmployeeYearendAdjustmentInsuranceSerializerCategory;
  /** 新旧区分<br>
区分が生命保険または個人年金保険の時のみ、新制度なら new を、旧制度なら old を指定します。<br>
上記以外の保険では none を指定してください。 */
  new_or_old?: ApiV1EmployeeYearendAdjustmentInsuranceSerializerNewOrOld;
  /**
   * 保険会社等の名称<br>
保険の種類にて、生命保険・介護医療保険・個人年金保険または地震保険・旧長期損害保険を選択している時のみ、入力した値が反映されます。<br>
上記以外の保険では入力した値は反映されません。
   * @maxLength 255
   * @nullable
   */
  company_name?: string | null;
  /**
   * 保険等の種類（目的）<br>
保険の種類にて、生命保険・介護医療保険・個人年金保険または地震保険・旧長期損害保険を選択している時のみ、入力した値が反映されます。<br>
上記以外の保険では入力した値は反映されません。
   * @maxLength 255
   * @nullable
   */
  kind_of_purpose?: string | null;
  /**
   * 保険期間又は年金支払期間<br>
保険の種類にて、生命保険・介護医療保険・個人年金保険または地震保険・旧長期損害保険を選択している時のみ、入力した値が反映されます。<br>
上記以外の保険では入力した値は反映されません。
   * @nullable
   */
  period?: ApiV1EmployeeYearendAdjustmentInsuranceSerializerPeriod;
  /**
   * 保険等の契約者 姓<br>
保険の種類にて、生命保険・介護医療保険・個人年金保険または地震保険・旧長期損害保険を選択している時のみ、入力した値が反映されます。<br>
上記以外の保険では入力した値は反映されません。
   * @maxLength 255
   * @nullable
   */
  policyholder_last_name?: string | null;
  /**
   * 保険等の契約者 名<br>
保険の種類にて、生命保険・介護医療保険・個人年金保険または地震保険・旧長期損害保険を選択している時のみ、入力した値が反映されます。<br>
上記以外の保険では入力した値は反映されません。
   * @maxLength 255
   * @nullable
   */
  policyholder_first_name?: string | null;
  /**
   * 保険金等の受取人 姓<br>
保険の種類にて、生命保険・介護医療保険・個人年金保険、地震保険・旧長期損害保険または社会保険を選択している時のみ、入力した値が反映されます。<br>
上記以外の保険では入力した値は反映されません。
   * @maxLength 255
   * @nullable
   */
  recipient_last_name?: string | null;
  /**
   * 保険金等の受取人 名<br>
保険の種類にて、生命保険・介護医療保険・個人年金保険、地震保険・旧長期損害保険または社会保険を選択している時のみ、入力した値が反映されます。<br>
上記以外の保険では入力した値は反映されません。
   * @maxLength 255
   * @nullable
   */
  recipient_first_name?: string | null;
  /**
   * 保険金等の受取人 あなたとの続柄 myself: 本人, husband: 夫, wife: 妻, father: 父, mother: 母, child: 子, senior_brother: 兄, junior_brother: 弟, senior_sister: 姉, junior_sister: 妹, grandchild: 孫, grandfather: 祖父, grandmother: 祖母, father_in_law: 義父, mother_in_law: 義母, grandfather_in_law: 義祖父, grandmother_in_law: 義祖母, other: その他, "": 空欄<br>
保険の種類にて、生命保険・介護医療保険・個人年金保険、地震保険・旧長期損害保険または社会保険を選択している時のみ、入力した値が反映されます。<br>
上記以外の保険では入力した値は反映されません。
   * @nullable
   */
  recipient_relationship?: ApiV1EmployeeYearendAdjustmentInsuranceSerializerRecipientRelationship;
  /**
   * 年金の支払開始日 1900年1月1日から現在年+100の12月31日まで登録可能。<br>
区分が個人年金保険の時のみ、入力した値が反映されます。<br>
上記以外の保険では入力した値は反映されません。
   * @nullable
   * @pattern ^([1-2][0-9]{3}-[0-9]{2}-[0-9]{2})?$
   */
  payment_start_date?: string | null;
  /**
   * 保険料額
   * @minimum 0
   * @maximum 99999999
   */
  amount?: number;
  /**
   * 電子的控除証明書などの認証方法を利用した場合、その認証方法が反映されます。<br>
xml: 電子的控除証明書を利用。証明書画像データの提出が免除されます。またrecipient_first_name、recipient_last_name、recipient_relationship以外のカラムが更新不可となります。
   * @nullable
   */
  certification_type?: ApiV1EmployeeYearendAdjustmentInsuranceSerializerCertificationType;
}
